### ISSUE TITLE
move react to devDeps

### ISSUE THREAD

**Issue by Guria** [rebem/test-utils#1]
React dependency could cause 2 react instances installed:
https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375#.wvy7xpwn2

**Comment by mistadikay** [comment]
It should be removed from both deps and peerDeps actually, because we use it only in tests. Commented in PR, closing the issue

**Comment by mistadikay** [comment]
It should be removed from both deps and peerDeps actually, because we use it only in tests. Commented in PR, I'll close this issue as soon as PR would be fixed and merged

**Comment by Guria** [comment]
leave here only `0.14.x` or also extend to `0.14.x || >=15.0.0-rc.1`?

**Comment by mistadikay** [comment]
in devDeps leave as it is right now please, we will upgrade devDeps later

**Comment by Guria** [comment]
done

**Comment by mistadikay** [comment]
@Guria released https://github.com/rebem/test-utils/releases/tag/v0.3.1
